### ISSUE TITLE
Plugin doesn't work?

### ISSUE THREAD

**Issue by DyonR** [iant89/UltimateNMZ#10]
I downloaded the plugin from the plugin hub, enabled it in Runelite, changed some settings to my liking, but it doesn't seem to do anything at all. I disabled the default NMZ plugin, disabled and enabled this one, but nothing appears on screen.  
Is it broken?

**Comment by DyonR** [comment]
Well, apparently you gotta enable it _before_ entering Nightmare Zone and it doesn't work when you enable it while you are already in. Awesome plugin, just started using it but looks amazing

**Comment by iant89** [comment]
It relies on chat logs to track when Nightmare Zone Starts, so If you enable it after it has started, I may have just disable session tracking or something. Thanks! Ill look into fixing it soon.
