### ISSUE TITLE
PLEASE implement OVERLOAD!

### ISSUE THREAD

**Issue by HFinner** [iant89/UltimateNMZ#2]
Just want to thank you for this plugin, I absolutely love it. 

I CANNOT AWAIT THE ARRIVAL OF THE OVERLOAD NOTIFICATION/SCREEN FLASHER.

Thanks!!!

**Comment by iant89** [comment]
Thank you!

I should be pushing my next update within the next few days. Overload is implemented, along with the option to use super combat pots, instead of overloads.
