### ISSUE TITLE
Option to hide entire overlay or each component of the overlay individually

### ISSUE THREAD

**Issue by hawkins** [iant89/UltimateNMZ#9]
Hi there! Absolutely love the plugin, thank you very very much for making and maintaining it!!

I love it for the notifications and awesome customizability, but I also find that the stock RuneLite "Nightmare Zone" plugin's overlay is more useful to me personally - it only shows points earned, points per hour, and total points, all precisely without rounding. I don't find this plugin's overlay very useful for me, since it rounds down (1,099,000 points = 1mil), and takes so much space to show hit points, overload, and session timers, plugin name, all of which are already on my screen elsewhere.

Would you consider making this overlay optional altogether, or individual elements each configurable with toggles to show/hide?

**Comment by hawkins** [comment]
P.S., while it doesn't suit *me*, I don't use NMZ much, I'm really not the target audience. I just want to imbue some stuff and get out. Just want to clarify that even though I personally didn't find a feature useful, it doesn't mean it's bad or redundant or anything negative at all. Overall it's really an awesome plugin and I really don't want my takes on the overlay to detract from that, but that's why I'm asking at all, because you've already done a bang up job making it this great already!

**Comment by iant89** [comment]
The Rounding issue I personally did not think about it bothering anyone, I just thought it made it easier on the eyes. Currently you can disable the "Override" and "Points per hour" and "Total Points" and it wont show anything point related.

The Overlay was already on my list to redesign, and should be finished in next few updates. So you will be able to show/hide individual components. Ill add the option to disable rounding, and fix the rounding issue.

The entire point of the "visual notifications" was to keep it behind the active window, or on another monitor. and the flashing would catch your attention. I usually put it on, and play with my kids. and will just glance up at it. Knowing the colors, along with the Icons I can know exactly what is going on. and not even half to be right there.

But Thank you for your feedback!
